apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-config
  namespace: confluent
type: Opaque
data:
  kafka.properties: "Ym9vdHN0cmFwLnNlcnZlcnM9a2Fma2Eub3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWw6OTA3MQpzYXNsLmphYXMuY29uZmlnPW9yZy5hcGFjaGUua2Fma2EuY29tbW9uLnNlY3VyaXR5LnBsYWluLlBsYWluTG9naW5Nb2R1bGUgcmVxdWlyZWQgdXNlcm5hbWU9a2Fma2EgcGFzc3dvcmQ9a2Fma2Etc2VjcmV0OwpzYXNsLm1lY2hhbmlzbT1QTEFJTgpzZWN1cml0eS5wcm90b2NvbD1TQVNMX1NTTApzc2wudHJ1c3RzdG9yZS5sb2NhdGlvbj0vbW50L3NzbGNlcnRzL3RydXN0c3RvcmUucDEyCnNzbC50cnVzdHN0b3JlLnBhc3N3b3JkPW15c3RvcmVwYXNzd29yZA=="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  namespace: confluent
spec:
  serviceName: elastic
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: confluentinc/cp-kafka:latest
          command:
            - /bin/sh
            - -c
            - |
              kafka-producer-perf-test \
                --topic ${HOSTNAME}  \
                --record-size 64 \
                --throughput 1 \
                --producer.config /mnt/kafka.properties \
                --num-records 230400
          volumeMounts:
            - name: kafka-properties
              mountPath: /mnt
              readOnly: true
            - name: kafka-pkcs12
              mountPath: /mnt/sslcerts
          resources:
            requests:
              memory: 512Mi # 768Mi
              cpu: 500m # 1000m
      volumes:
        - name: kafka-properties # Create secret with name `kafka-client-config` with client configurations
          secret:
            secretName: kafka-client-config
        - name: kafka-pkcs12
          secret:
            secretName: kafka-pkcs12
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: confluent
spec:
  clusterIP: None
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: elastic-0
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 1
  kafkaRestRef:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
  configs:
    cleanup.policy: "delete"