apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: gitOps4Life
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 10
  configs:
    cleanup.policy: "delete"
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: confluentRulez
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 10
  configs:
    cleanup.policy: "delete"